/**
 * Build-time symbol seed.
 *
 * `generateStaticParams` pre-renders these at build; every other symbol
 * renders on demand and is then cached by ISR. The list is committed
 * rather than fetched from the backend at build time on purpose — a
 * backend outage during a deploy would otherwise produce a build with
 * zero pre-rendered stock pages, or fail the build outright.
 *
 * Sourced from the backend's index constituent lists. Refresh after each
 * NSE semi-annual rebalance.
 */

export const SEED_SYMBOLS: ReadonlyArray<readonly [symbol: string, name: string]> = [
  ["RELIANCE", "Reliance Industries"],
  ["HDFCBANK", "HDFC Bank"],
  ["BHARTIARTL", "Bharti Airtel"],
  ["SBIN", "State Bank of India"],
  ["ICICIBANK", "ICICI Bank"],
  ["TCS", "Tata Consultancy Services"],
  ["BAJAJFINSV", "Bajaj Finserv"],
  ["LT", "Larsen & Toubro"],
  ["HINDUNILVR", "Hindustan Unilever"],
  ["INFY", "Infosys"],
  ["AXISBANK", "Axis Bank"],
  ["MARUTI", "Maruti Suzuki"],
  ["TITAN", "Titan Company"],
  ["NTPC", "NTPC"],
  ["SUNPHARMA", "Sun Pharmaceutical"],
  ["ITC", "ITC"],
  ["M&M", "Mahindra & Mahindra"],
  ["KOTAKBANK", "Kotak Mahindra Bank"],
  ["ADANIPORTS", "Adani Ports"],
  ["ONGC", "ONGC"],
  ["ULTRACEMCO", "UltraTech Cement"],
  ["HCLTECH", "HCL Technologies"],
  ["BEL", "Bharat Electronics"],
  ["JSWSTEEL", "JSW Steel"],
  ["ADANIENTERP", "Adani Enterprises"],
  ["POWERGRID", "Power Grid Corporation"],
  ["BAJFINANCE", "Bajaj Finance"],
  ["COALINDIA", "Coal India"],
  ["NESTLEIND", "Nestle India"],
  ["BAJAJAUTO", "Bajaj Auto"],
  ["TATASTEEL", "Tata Steel"],
  ["ZOMATO", "Zomato"],
  ["ASIANPAINT", "Asian Paints"],
  ["SHRIRAMFIN", "Shriram Finance"],
  ["HINDALCO", "Hindalco Industries"],
  ["WIPRO", "Wipro"],
  ["EICHERMOT", "Eicher Motors"],
  ["GRASIM", "Grasim Industries"],
  ["SBILIFE", "SBI Life Insurance"],
  ["INDIGO", "IndiGo"],
  ["JIOFINSV", "Jio Financial Services"],
  ["TRENT", "Trent"],
  ["TECHM", "Tech Mahindra"],
  ["TATAMOTORS", "Tata Motors"],
  ["HDFCLIFE", "HDFC Life Insurance"],
  ["TATACONSUM", "Tata Consumer Products"],
  ["APOLLOHOSP", "Apollo Hospitals"],
  ["CIPLA", "Cipla"],
  ["MAXHEALTH", "Max Healthcare"],
  ["ADANIGREEN", "Adani Green Energy"],
  ["ADANIPOWER", "Adani Power"],
  ["AMBUJACEM", "Ambuja Cements"],
  ["BAJAJHLDNG", "Bajaj Holdings"],
  ["BERGEPAINT", "Berger Paints"],
  ["BPCL", "BPCL"],
  ["BRITANNIA", "Britannia Industries"],
  ["CANBK", "Canara Bank"],
  ["CHOLAFIN", "Cholamandalam Investment"],
  ["DLF", "DLF"],
  ["GAIL", "GAIL India"],
  ["GODREJCP", "Godrej Consumer Products"],
  ["HAVELLS", "Havells India"],
  ["HEROMOTOCO", "Hero MotoCorp"],
  ["HINDZINC", "Hindustan Zinc"],
  ["INDHOTEL", "Indian Hotels"],
  ["IOC", "Indian Oil Corporation"],
  ["IRCTC", "IRCTC"],
  ["LICHSGFIN", "LIC Housing Finance"],
  ["LUPIN", "Lupin"],
  ["MANKIND", "Mankind Pharma"],
  ["MUTHOOTFIN", "Muthoot Finance"],
  ["OFSS", "Oracle Financial Services"],
  ["PIIND", "PI Industries"],
  ["PIDILITIND", "Pidilite Industries"],
  ["PNB", "Punjab National Bank"],
  ["POLYCAB", "Polycab India"],
  ["RECLTD", "REC"],
  ["SBICARD", "SBI Cards"],
  ["SHREECEM", "Shree Cement"],
  ["SIEMENS", "Siemens"],
  ["TATAPOWER", "Tata Power"],
  ["TORNTPHARM", "Torrent Pharmaceuticals"],
  ["UPL", "UPL"],
  ["VEDL", "Vedanta"],
  ["VBL", "Varun Beverages"],
  ["ZYDUSLIFE", "Zydus Lifesciences"],
  ["JIOFIN", "Jio Financial Services"],
  ["FEDERALBNK", "Federal Bank"],
  ["NAUKRI", "Info Edge"],
  ["DMART", "Avenue Supermarts"],
  ["PERSISTENT", "Persistent Systems"],
  ["BANKBARODA", "Bank of Baroda"],
  ["UNIONBANK", "Union Bank of India"],
  ["AUBANK", "AU Small Finance Bank"],
  ["INDUSINDBK", "IndusInd Bank"],
  ["YESBANK", "Yes Bank"],
  ["IDFCFIRSTB", "IDFC First Bank"],
  ["LTIM", "LTIMindtree"],
  ["COFORGE", "Coforge"],
  ["MPHASIS", "Mphasis"],
  ["DIVISLAB", "Divi's Laboratories"],
  ["AUROPHARMA", "Aurobindo Pharma"],
  ["GLENMARK", "Glenmark Pharmaceuticals"],
  ["ALKEM", "Alkem Laboratories"],
  ["LAURUSLABS", "Laurus Labs"],
  ["BIOCON", "Biocon"],
  ["ABBOTINDIA", "Abbott India"],
  ["IPCALAB", "IPCA Laboratories"],
  ["AJANTPHARM", "Ajanta Pharma"],
  ["JBCHEPHARM", "JB Chemicals & Pharma"],
  ["GLAND", "Gland Pharma"],
  ["WOCKPHARMA", "Wockhardt"],
  ["PPLPHARMA", "Piramal Pharma"],
  ["TVSMOTOR", "TVS Motor Company"],
  ["MOTHERSON", "Samvardhana Motherson"],
  ["BOSCHLTD", "Bosch"],
  ["ASHOKLEY", "Ashok Leyland"],
  ["BHARATFORG", "Bharat Forge"],
  ["UNOMINDA", "Uno Minda"],
  ["TIINDIA", "Tube Investments of India"],
  ["SONACOMS", "Sona BLW Precision"],
  ["EXIDEIND", "Exide Industries"],
  ["MARICO", "Marico"],
  ["MCDOWELL-N", "United Spirits"],
  ["DABUR", "Dabur India"],
  ["COLPAL", "Colgate-Palmolive India"],
  ["PATANJALI", "Patanjali Foods"],
  ["RADICO", "Radico Khaitan"],
  ["UBL", "United Breweries"],
  ["EMAMILTD", "Emami"],
  ["JINDALSTEL", "Jindal Steel & Power"],
  ["LLOYDSENGG", "Lloyds Metals & Energy"],
  ["NATIONALUM", "National Aluminium"],
  ["NMDC", "NMDC"],
  ["SAIL", "Steel Authority of India"],
  ["JSL", "Jindal Stainless"],
  ["APLAPOLLO", "APL Apollo Tubes"],
  ["HINDCOPPER", "Hindustan Copper"],
  ["WELCORP", "Welspun Corp"],
  ["LODHA", "Macrotech Developers"],
  ["PHOENIXLTD", "Phoenix Mills"],
  ["OBEROIRLTY", "Oberoi Realty"],
  ["PRESTIGE", "Prestige Estates"],
  ["GODREJPROP", "Godrej Properties"],
  ["BRIGADE", "Brigade Enterprises"],
  ["ANANTRAJ", "Anant Raj"],
  ["ABREL", "Aditya Birla Real Estate"],
  ["SOBHA", "Sobha"],
  ["ADANIENSOL", "Adani Energy Solutions"],
  ["ABB", "ABB India"],
  ["POWERINDIA", "ABB Power Products"],
  ["CGPOWER", "CG Power & Industrial"],
  ["GET&D", "GE Vernova T&D India"],
  ["BHEL", "BHEL"],
  ["JSWENERGY", "JSW Energy"],
  ["TORNTPOWER", "Torrent Power"],
  ["NHPC", "NHPC"],
  ["HINDPETRO", "HPCL"],
  ["OIL", "Oil India"],
  ["SUZLON", "Suzlon Energy"],
  ["ATGL", "Adani Total Gas"],
  ["THERMAX", "Thermax"],
  ["NLCINDIA", "NLC India"],
  ["PETRONET", "Petronet LNG"],
  ["SJVN", "SJVN"],
  ["AEGISLOG", "Aegis Logistics"],
  ["CESC", "CESC"],
  ["IGL", "Indraprastha Gas"],
  ["CASTROLIND", "Castrol India"],
  ["INOXWIND", "Inox Wind"],
  ["GSPL", "Gujarat State Petronet"],
  ["JPPOWER", "Jaiprakash Power"],
  ["RPOWER", "Reliance Power"],
  ["CUMMINSIND", "Cummins India"],
  ["INDUSTOWER", "Indus Towers"],
  ["FORTIS", "Fortis Healthcare"],
  ["BSE", "BSE"],
  ["GMRAIRPORT", "GMR Airports"],
  ["WAAREEENER", "Waaree Energies"],
  ["ICICIGI", "ICICI Lombard"],
  ["SWIGGY", "Swiggy"],
  ["POLICYBZR", "PB Fintech"],
  ["NYKAA", "FSN E-Commerce (Nykaa)"],
  ["SRF", "SRF"],
  ["PAYTM", "Paytm"],
  ["MCX", "MCX"],
  ["DIXON", "Dixon Technologies"],
  ["MFSL", "Max Financial Services"],
  ["SUPREMEIND", "Supreme Industries"],
];

const NAME_BY_SYMBOL = new Map<string, string>(SEED_SYMBOLS as ReadonlyArray<[string, string]>);

/** Company name for a seeded symbol, used for metadata before the API answers. */
export function seededName(symbol: string): string | null {
  return NAME_BY_SYMBOL.get(symbol.toUpperCase()) ?? null;
}
